#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-mnormt
Version  : 2.1.1
Release  : 59
URL      : https://cran.r-project.org/src/contrib/mnormt_2.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/mnormt_2.1.1.tar.gz
Summary  : The Multivariate Normal and t Distributions, and Their Truncated
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-mnormt-lib = %{version}-%{release}
Requires: R-mnormt-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
distribution function of d-dimensional normal and "t" random variables,
  possibly truncated (on one side or two sides),  and for generating random 
  vectors sampled from these distributions, except sampling from the truncated
  "t". Moments of arbitrary order of a multivariate truncated normal are
  computed, and converted to cumulants up to order 4. 
  Probabilities are computed via non-Monte Carlo methods; different routines 
  are used in the case d=1, d=2, d=3, d>3, if d denotes the dimensionality.

%package lib
Summary: lib components for the R-mnormt package.
Group: Libraries
Requires: R-mnormt-license = %{version}-%{release}

%description lib
lib components for the R-mnormt package.


%package license
Summary: license components for the R-mnormt package.
Group: Default

%description license
license components for the R-mnormt package.


%prep
%setup -q -n mnormt
pushd ..
cp -a mnormt buildavx2
popd
pushd ..
cp -a mnormt buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737151234

%install
export SOURCE_DATE_EPOCH=1737151234
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-mnormt
cp %{_builddir}/mnormt/COPYING %{buildroot}/usr/share/package-licenses/R-mnormt/17e3b0eea99abffe6ac71e65627413236e0b117a || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mnormt/CITATION
/usr/lib64/R/library/mnormt/DESCRIPTION
/usr/lib64/R/library/mnormt/INDEX
/usr/lib64/R/library/mnormt/Meta/Rd.rds
/usr/lib64/R/library/mnormt/Meta/features.rds
/usr/lib64/R/library/mnormt/Meta/hsearch.rds
/usr/lib64/R/library/mnormt/Meta/links.rds
/usr/lib64/R/library/mnormt/Meta/nsInfo.rds
/usr/lib64/R/library/mnormt/Meta/package.rds
/usr/lib64/R/library/mnormt/NAMESPACE
/usr/lib64/R/library/mnormt/NEWS.Rd
/usr/lib64/R/library/mnormt/R/mnormt
/usr/lib64/R/library/mnormt/R/mnormt.rdb
/usr/lib64/R/library/mnormt/R/mnormt.rdx
/usr/lib64/R/library/mnormt/help/AnIndex
/usr/lib64/R/library/mnormt/help/aliases.rds
/usr/lib64/R/library/mnormt/help/mnormt.rdb
/usr/lib64/R/library/mnormt/help/mnormt.rdx
/usr/lib64/R/library/mnormt/help/paths.rds
/usr/lib64/R/library/mnormt/html/00Index.html
/usr/lib64/R/library/mnormt/html/R.css
/usr/lib64/R/library/mnormt/notice-Genz

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/mnormt/libs/mnormt.so
/V4/usr/lib64/R/library/mnormt/libs/mnormt.so
/usr/lib64/R/library/mnormt/libs/mnormt.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-mnormt/17e3b0eea99abffe6ac71e65627413236e0b117a
